Repository akshitadixit/VCallZer, pull requests merged in 2021-06, with the labels that each got.

#13 Issue number #9 is solved, Readme file updated with contribution Info
  README.md
Labels: LGMSOC21, 🟩 Level1

#17 Generated a requirements.txt
  requirements.txt
Labels: LGMSOC21, 🟨 Level2

#18 Updating README.md to change contributor-section
  README.md
Labels: LGMSOC21, 🟩 Level1

#19 Added myself as contributor
  README.md
Labels: LGMSOC21, 🟩 Level1

#26 Added GitHub Watcher badge
  README.md
Labels: LGMSOC21, 🟩 Level1

#28 Issue number #4 re-solved added myself as a contributor
  README.md
Labels: LGMSOC21, 🟩 Level1

#22 Issue Number #4 added myself as contributor
  README.md
Labels: LGMSOC21, 🟩 Level1

#32 Major Update README.md
  README.md
Labels: LGMSOC21, 🟩 Level1

#31 Update greetings.yml
  .github/workflows/greetings.yml
Labels: LGMSOC21, 🟧 Level3

#30 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: LGMSOC21, 🟩 Level1

#36 Added comments for GUI.py, Client.py, and small updates in Readme.md
  client.py
  gui.py
Labels: LGMSOC21, 🟩 Level1

#45 added links to badges and aligned them
  README.md
Labels: LGMSOC21, 🟩 Level1

#48 Updated my avatar in Readme.md
  README.md
Labels: LGMSOC21, 🟩 Level1

#54 Added PR template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: LGMSOC21, 🟩 Level1
